config/routes.rb
Rails.application.routes.draw do
  resources :books

get "home/index"
get "home/index2"
get "home/index3"

end

app/models/MyModel.rb
#class MyModel
  #after_update :reload_page

  #def reload_page
    ### Code to reload page
  #end
#end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :year)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <td><%= book.year %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Year:</strong>
  <%= @book.year %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/home/index.html.erb
<html>
<head>
<title>Hi this is html refresh test</title>
<meta http-equiv="refresh" content="5" />
</head>
<body>
Hi Ratikkk
</body>
</html>

app/views/home/index2.html.erb
All the Environmemnts are up & running, you may go for a coffee
<html>
<title>
A script to generate html report
</title>
<meta http-equiv=refresh content=5 />
<table border=4>
<tr>
<th>
Env Name
</th>
<th>
URL
</th>
<th>
Status
</th>
<th>
Verification Date
</th>
<th>
Verification Time
</th>
<th>
Release Num
</th>
<th>
ENV
</th>
</tr>
</table>
</body>
</html>
<body bgcolor=#E6E6FA>
</body>

app/views/home/index3.html.erb
Environmemnts are down, please fix before you go for Tea 
All the Environmemnts are up & running, you may go for a coffee
<html>
<title>
A script to generate html report
</title>
<meta http-equiv=refresh content=5 />
<table border=4>
<tr>
<th>
Env Name
</th>
<th>
URL
</th>
<th>
Status
</th>
<th>
Verification Date
</th>
<th>
Verification Time
</th>
<th>
Release Num
</th>
<th>
ENV
</th>
</tr>
</table>
</body>
</html>
<body bgcolor=#E6E6FA>
</body>

app/views/home/index4.html.erb
Environmemnts are down, please fix before you go for a coffee
<html>
<title>
A script to generate html report
</title>
<table border=4>
<tr>
<th>
Env Name
</th>
<th>
URL
</th>
<th>
Status
</th>
<th>
Verification Date
</th>
<th>
Verification Time
</th>
<th>
Release Num
</th>
</tr>
<tr>
<td>
iDEV11-YTBP(VIP)
</td>
<td>
<a href='http://ytb-idev11-vip.hhscie.txaccess.net/wps/portal'>http://ytb-idev11-vip.hhscie.txaccess.net/wps/portal</a>
</td>
<td>
<p style="color:#FF0000";>DOWN </p>
</td>
<td>
2017-06-04
</td>
<td>
2017-06-04:20:42:28
</td>
<td>
R100.0.0.0
</td>
</tr>
<tr>
<td>
iDEV11-YTBP(Node1)
</td>
<td>
<a href='http://cwaa700:14539/wps/portal'>http://cwaa700:14539/wps/portal</a>
</td>
<td>
UP
</td>
<td>
2017-06-04
</td>
<td>
2017-06-04:20:42:28
</td>
<td>
R100.0.0.0
</td>
</tr>
<tr>
<td>
iDEV11-YTBP(Node2)
</td>
<td>
<a href='http://cwaa701:14539/wps/portal'>http://cwaa701:14539/wps/portal</a>
</td>
<td>
<p style="color:#FF0000";>DOWN</p>
</td>
<td>
2017-06-04
</td>
<td>
2017-06-04:20:42:28
</td>
<td>
R100.0.0.0
</td>
</tr>
<tr>
<td>
iDEV11-YTBSvc(VIP)
</td>
<td>
<a href='http://ytbsvc-idev11-vip.hhscie.txaccess.net/service/DTC/api/finanoffice/retreive'>http://ytbsvc-idev11-vip.hhscie.txaccess.net/service/DTC/api/finanoffice/retreive</a>
</td>
<td>
UP
</td>
<td>
2017-06-04
</td>
<td>
2017-06-04:20:42:28
</td>
<td>
R100.0.0.0
</td>
</tr>
<tr>
<td>
iDEV11-YTBSvc(Node1)
</td>
<td>
<a href='http://cwaa702:10512/service/DTC/api/finanoffice/retreive'>http://cwaa702:10512/service/DTC/api/finanoffice/retreive</a>
</td>
<td>
UP
</td>
<td>
2017-06-04
</td>
<td>
2017-06-04:20:42:28
</td>
<td>
R100.0.0.0
</td>
</tr>
<tr>
<td>
iDEV11-YTBSvc(Node2)
</td>
<td>
<a href='http://cwaa703:10512/service/DTC/api/finanoffice/retreive'>http://cwaa703:10512/service/DTC/api/finanoffice/retreive</a>
</td>
<td>
UP
</td>
<td>
2017-06-04
</td>
<td>
2017-06-04:20:42:28
</td>
<td>
R100.0.0.0
</td>
</tr>
<tr>
<td>
iDEV11-SDCP(VIP)
</td>
<td>
<a href='http://sdc-idev11-vip.hhscie.txaccess.net/wps/portal'>http://sdc-idev11-vip.hhscie.txaccess.net/wps/portal</a>
</td>
<td>
UP
</td>
<td>
2017-06-04
</td>
<td>
2017-06-04:20:42:28
</td>
<td>
R100.0.0.0
</td>
</tr>
<tr>
<td>
iDEV11-SDCP(Node1)
</td>
<td>
<a href='http://cwaa704:14539/wps/portal'>http://cwaa704:14539/wps/portal</a>
</td>
<td>
UP
</td>
<td>
2017-06-04
</td>
<td>
2017-06-04:20:42:28
</td>
<td>
R100.0.0.0
</td>
</tr>
<tr>
<td>
iDEV11-SDCP(Node2)
</td>
<td>
<a href='http://cwaa705:14539/wps/portal'>http://cwaa705:14539/wps/portal</a>
</td>
<td>
UP
</td>
<td>
2017-06-04
</td>
<td>
2017-06-04:20:42:28
</td>
<td>
R100.0.0.0
</td>
</tr>
<tr>
<td>
iDEV11-SDCSvc(VIP)
</td>
<td>
<a href='http://sdcsvc-idev11-vip.hhscie.txaccess.net/Service/LTSSClientInformationService'>http://sdcsvc-idev11-vip.hhscie.txaccess.net/Service/LTSSClientInformationService</a>
</td>
<td>
UP
</td>
<td>
2017-06-04
</td>
<td>
2017-06-04:20:42:28
</td>
<td>
R100.0.0.0
</td>
</tr>
<tr>
<td>
iDEV11-SDCSvc(Node1)
</td>
<td>
<a href='http://cwaa706:11512/Service/LTSSClientInformationService'>http://cwaa706:11512/Service/LTSSClientInformationService</a>
</td>
<td>
UP
</td>
<td>
2017-06-04
</td>
<td>
2017-06-04:20:42:28
</td>
<td>
R100.0.0.0
</td>
</tr>
<tr>
<td>
iDEV11-SDCSvc(Node2)
</td>
<td>
<a href='http://cwaa707:11512/Service/LTSSClientInformationService'>http://cwaa707:11512/Service/LTSSClientInformationService</a>
</td>
<td>
UP
</td>
<td>
2017-06-04
</td>
<td>
2017-06-04:20:42:28
</td>
<td>
R100.0.0.0
</td>
</tr>
</table>
</body>
</html>
<body bgcolor=#E6E6FA>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ratik</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>